version: '3'
services:
  chatapp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=your_jwt_secret
      - MONGO_URI=mongodb://mongo:27017/chatapp
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
