
# Register
# POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "test",
  "email": "testuser@example.com",
  "password": "testpassword"
}


# Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "testpassword"
}